language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
branches:
  except:
    - fit-pages
before_script:
  - "cp -v config/database.${DB}.yml config/database.yml"
  - "cp -v config/crewmate.example.yml config/crewmate.yml"
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
script: "bundle exec rake spec"
matrix:
  allow_failures:
    - rvm: 2.0.0
addons:
  code_climate:
    repo_token: 74d9b568038c718984353cf6e8c54a8b151f87af24ae6eab5791bc2d00dc6211
